services:
  ollama:
    image: ollama/ollama:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [compute, utility]
    ports: 
       - "11434:11434"
    network_mode: "host"
    volumes:
       - ./ollama:/root/.ollama
