services:
  ollama:
    image: ollama/ollama:latest
    container_name: conspecter_ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [compute, utility]
    ports: 
       - "11434:11434"
    network_mode: "host"
    volumes:
       - ./ollama:/root/.ollama
  frontend:
    image: git.mootfrost.dev/aireader/web-app_frontend:latest
    container_name: conspecter_frontend
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.mootfrost_dev.rule=Host(`read.mootfrost.dev`)
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - OLLAMA_API_KEY=${OLLAMA_API_KEY}
    build: .
    ports:
      - "7778:80"